improve install script
now on:
- script warns user to preffer deb packaging method to install
- if already installed by deb package, interrupts and instructs user
  to remove previous intallation first

diff --git a/install b/install
--- a/install
+++ b/install
@@ -19,6 +19,39 @@ __SCRIPT_NAME__="install"
 # from project-header file
 source ./tip-notes/project-header.sh
 
+echo
+echo "ATTENTION!"
+echo
+echo "We strongly recommend to always install and remove ${__project_name__}"
+echo "trough assistance of system packaging manager. Please check README.md"
+echo "installation section to see how to do it!"
+echo
+read -p "Ignore this warning and install? Type 'YES' to proceed: " answer
+echo
+if [[ "${answer}" != 'YES' ]]; then
+    echo "Installation aborted by user!"
+    echo
+    exit 1
+fi
+
+# aborts if already installed by apt
+if apt list --installed 2> /dev/null | grep 'tip-notes'; then
+    echo
+    echo "ATTENTION!"
+    echo
+    echo\
+        "${__project_name__} has already been installed using apt system's"\
+        "package manager!"
+    echo
+    echo "Remove installed version using:"
+    echo
+    echo "sudo apt remove tip-notes"
+    echo
+    echo "then, call this script again"
+    echo
+    exit 1
+fi
+
 
 # if any command line parameter has been passed display help message
 if [[ $# -gt 0 ]]; then
