add confirmation to --delete option

diff --git a/tip-notes/tip b/tip-notes/tip
--- a/tip-notes/tip
+++ b/tip-notes/tip
@@ -40,6 +40,7 @@ tip_editor=''
 tip_confirm_remove=true
 tip_confirm_remove_purge=true
 tip_confirm_config_reset=true
+tip_confirm_delete_note=true
 
 # if exist a config file, source it
 if [[ -f "${tip_config_file}" ]]; then
@@ -144,6 +145,15 @@ while [[ ${#} -gt 0 ]]; do
             fi
             note_file="${tip_notes_folder}/${1}"
             if [[ -f "${note_file}" ]]; then
+                if [ "${tip_confirm_delete_note}" = true ]; then
+
+                    read -p "Are you sure? (y/n): " answer
+                    if ! [[ "${answer}" =~ [y|Y] ]]; then
+                        echo "reset operation aborted by user!"
+                        exit 1
+                    fi
+
+                fi
                 rm "${note_file}"
             else
                 echo "no ${1} note to be removed!"
