rename options, variables and files
option renamed:
--remove-purge           --> --purge
--config-init            --> --init
--config-reset           --> --reset

variables renamed
tip_confirm_remove_purge --> tip_confirm_purge
tip_confirm_config_reset --> tip_confirm_reset

files renamed:
config-init              --> init

diff --git a/tip-notes/tip b/tip-notes/tip
--- a/tip-notes/tip
+++ b/tip-notes/tip
@@ -53,15 +53,12 @@ source ./project-header.sh
 if [[ -f "${__project_config_file__}" ]]; then
     source "${__project_config_file__}"
 else
-    if [[ "${#}" -eq 0 ]] || [[ "${1}" != '--config-init' ]]; then
+    if [[ "${#}" -eq 0 ]] || [[ "${1}" != '--init' ]]; then
         echo
         echo "ERROR: --> configuration file does not exist!"
         echo
         echo "To fix it type:"
-        echo "tip --config-init"
-        echo
-        echo "then, if  required:"
-        echo "tip --config"
+        echo "tip --init"
         echo
         exit 1
     fi
@@ -129,9 +126,9 @@ while [[ ${#} -gt 0 ]]; do
             echo "${__script_name__} [<group>]                          list all notes within the group"
             echo "${__script_name__} [[<group>]/]<note>                 list specific note"
             echo
-            echo "${__script_name__} --config-init                      create an external configuration file"
-            echo "${__script_name__} --config-reset                     reset external configuration file"
             echo "${__script_name__} --config                           edit external configuration file"
+            echo "${__script_name__} --init                             create an external configuration file"
+            echo "${__script_name__} --reset                            reset external configuration file"
             echo
             echo "${__script_name__} --edit [[<group>]/]<note>          add/edit note"
             echo "${__script_name__} --delete [[<group>]/]<note>        delete note"
@@ -139,7 +136,7 @@ while [[ ${#} -gt 0 ]]; do
             echo "${__script_name__} --find-content [<group>] <text>    find notes which contains <text>"
             echo
             echo "${__script_name__} --remove                           remove ${__project_name__} from system"
-            echo "${__script_name__} --remove-purge                     remove ${__project_name__} from system including"
+            echo "${__script_name__} --purge                            remove ${__project_name__} from system including"
             echo "                                       configuration files and notes"
             echo
             echo "${__script_name__} --version                          shows ${__project_name__} version"
@@ -272,12 +269,12 @@ while [[ ${#} -gt 0 ]]; do
             echo
             exit 1
             ;;
-        '--config-init')
-            ./config-init
+        '--init')
+            ./init
             exit 0
             ;;
-        '--config-reset')
-            if [ "${tip_confirm_config_reset}" = true ]; then
+        '--reset')
+            if [ "${tip_confirm_reset}" = true ]; then
                 read -p "Are you sure? (y/n): " answer
                 if ! [[ "${answer}" =~ [y|Y] ]]; then
                     echo "reset operation aborted by user!"
@@ -285,14 +282,28 @@ while [[ ${#} -gt 0 ]]; do
                 fi
             fi
             rm "${__project_config_file__}"
-            ./config-init
+            ./init
             exit 0
             ;;
         '--remove')
+            if [ "${tip_confirm_remove}" = true ]; then
+                read -p "Are you sure? (y/n): " answer
+                if ! [[ "${answer}" =~ [y|Y] ]]; then
+                    echo "reset operation aborted by user!"
+                    exit 1
+                fi
+            fi
             ./remove
             exit 0
             ;;
-        '--remove-purge')
+        '--purge')
+            if [ "${tip_confirm_purge}" = true ]; then
+                read -p "Are you sure? (y/n): " answer
+                if ! [[ "${answer}" =~ [y|Y] ]]; then
+                    echo "reset operation aborted by user!"
+                    exit 1
+                fi
+            fi
             ./remove --purge
             exit 0
             ;;
